services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: python app.py
    volumes:
      - ./backend/src:/app
    depends_on:
      - db
  
  downloader-manager:
    build: ./backend
    command: python downloader.py
    volumes:
      - ./backend/src:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  
  downloader-worker-1:
    build: ./backend
    command: python downloader.py
    volumes:
      - ./backend/src:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WORKER=1
    depends_on:
      - db
      - redis
      - downloader-manager

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ytmusic
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: