services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: python app.py
    volumes:
      - ./backend/src:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ytmp3
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: